[package]
name = "multiplayer-tictactoe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
actix-web-lab = "0.18.9"
env_logger = "0.10.0"
nanoid = "0.4.0"
